# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Research Methods in Digital Humanities
email: libby.hemphill@iit.edu
description: "Time: MW 1:50pm, Location: Wishnick 315"
baseurl: "/research-methods-in-digital-humanities" # the subpath of your site, e.g. /blog
url: "http://libby.github.io" # the base hostname & protocol for your site
github_username:  libbyh

# Build settings
markdown: kramdown
